FROM bughunter-base:latest

# Install API utilities
# Swagger and GraphQL utilities placeholder
# Using generic pip installation for common tools
RUN pip3 install --break-system-packages graphql-cop inql

CMD ["/bin/bash"]
